version: "3.9"

services:
  database:
    image: "postgres:alpine"
    container_name: database_rentx
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=tests
      - POSTGRES_PASSWORD=rentx123
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres

  redis:
    image: "redis:alpine"
    container_name: redis_rentx
    ports:
      - 6379:6379

  # app:
  #   build: .
  #   container_name: rentx
  #   restart: always
  #   ports:
  #     - 5500:5500
  #   volumes:
  #     - .:/usr/app
  #   links:
  #     - database
  #   depends_on:
  #     - database


# mapping volumes
volumes:
  pgdata:
    driver: local

# to init: docker-compose up
# to init in background: docker-compose up -d
# network refused error: docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}'
#   or docker exec CONTAINER_NAME cat /etc/hosts
